### ISSUE TITLE
On fresh clone autocoder does not run?

### ISSUE THREAD

**Issue by ljreder** [JPLOpenSource/STARS#3]
@garthwatney not sure what is going on.  Using my JPL mac.   All Python modules looked ok

```
(STARS) reder@MT-316925 STARS % pip list
Package    Version
---------- -----------
anytree    2.12.1
Cheetah3   3.2.6.post1
httplib2   0.22.0
lxml       5.1.0
pip        24.2
plantuml   0.3.0
pyparsing  3.1.1
setuptools 65.5.0
six        1.16.0
```
Running the make looks like this

```
(STARS) reder@MT-316925 STARS % make
/Library/Developer/CommandLineTools/usr/bin/make -C models
cd TestModels/simple && make
cd QM-C && make clean && make
rm -rf test
rm -rf *.o
rm -rf *.c
rm -rf *.h
**** Running the state-machine autocoder ****
../../../../autocoder/Stars.py -backend c  -model ../Simple.qm
Traceback (most recent call last):
  File "/Users/reder/STARS/STARS/models/TestModels/simple/QM-C/../../../../autocoder/Stars.py", line 91, in <module>
    import fprime_backend.fprimecoder as fprimecoder
  File "/Users/reder/STARS/STARS/autocoder/fprime_backend/fprimecoder.py", line 19, in <module>
    from pydantic import BaseModel
ModuleNotFoundError: No module named 'pydantic'
make[3]: *** [autocode] Error 1
make[2]: *** [QM-C-depend] Error 2
make[1]: *** [simple-depend] Error 2
make: *** [all] Error 2
```
Note I am on the main branch.  Please let me know how to get this all working again on both my computers and I will try to evaluate it a bit and help.

**Comment by garthwatney** [comment]
Fixed bbc70d8dd11ac37152f90003e74f64c65b5f184e
